# frontend-service.yaml (Updated to ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:  
  type: ClusterIP  # Only accessible from within the cluster (by Ingress)
  selector:
    app: todo-frontend
  ports:
    - port: 3000
      targetPort: 3000